### ISSUE TITLE
'gulp build' issues

### ISSUE THREAD

**Issue by NathanielPrescott** [CrouchingJahi/Cyril-old#24]
MacBook Pro (Retina, 15-inch, Mid 2014)
Version 10.11.16

sudo gulp build
[21:52:06] Using gulpfile ~/MyFiles/GitHub/Cyril/gulpfile.js
[21:52:06] Starting 'build:css'...
[21:52:06] Finished 'build:css' after 8.94 ms
[21:52:06] Starting 'build'...
[21:52:06] Finished 'build' after 11 μs
/Users/nprescott/MyFiles/GitHub/Cyril/node_modules/dart-sass/sass.dart.js:21240
          throw exception;
          ^

TypeError: utf8 is not a function
    at Function.from (native)
    at Function.from (native)
    at dart._render (/Users/nprescott/MyFiles/GitHub/Cyril/node_modules/dart-sass/sass.dart.js:21232:39)
    at dart.Primitives_applyFunctionWithPositionalArguments (/Users/nprescott/MyFiles/GitHub/Cyril/node_modules/dart-sass/sass.dart.js:4076:28)
    at dart._callDartFunctionFast (/Users/nprescott/MyFiles/GitHub/Cyril/node_modules/dart-sass/sass.dart.js:13281:16)
    at Object.render (/Users/nprescott/MyFiles/GitHub/Cyril/node_modules/dart-sass/sass.dart.js:13273:18)
    at Transform._transform (/Users/nprescott/MyFiles/GitHub/Cyril/gulpfile.js:35:10)
    at Transform._read (/Users/nprescott/MyFiles/GitHub/Cyril/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at Transform._write (/Users/nprescott/MyFiles/GitHub/Cyril/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:172:12)
    at doWrite (/Users/nprescott/MyFiles/GitHub/Cyril/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:237:10)

**Comment by CrouchingJahi** [comment]
Try updating your dart-sass dependency - `yarn upgrade dart-sass` or `npm update dart-sass`. Since it's in alpha releases, I don't think npm is correctly selecting the latest.

**Comment by CrouchingJahi** [comment]
Resolved: He was using an old version of Node. Switching over to 6.9.x eliminates this error.
